# @package _global_
logger:
  - _target_: src.callbacks.logger.WandBLogger
    project: torchrl-hydra-template
    entity: null                # set via env var WANDB_ENTITY or CLI override
    name: ${hydra:runtime.choices.algorithm}_${hydra:runtime.choices.environment}_${now:%Y-%m-%d_%H-%M-%S}
    tags: []
    mode: online                # "online" | "offline" | "disabled"
    save_dir: ${paths.log_dir}/wandb/
