defaults:
  - _self_
  - algorithm: ???
  - environment: ???
  - logger: []
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

trainer:
  accelerator: cpu
  devices: [0]
  seed: 42
  num_eval_episodes: 10

checkpoint:
  resume_from: ???        # required: path to checkpoint file

hydra:
  run:
    dir: logs/eval/${now:%Y-%m-%d_%H-%M-%S}
